### ISSUE TITLE
GeometryCollection support

### ISSUE THREAD

**Issue by ilyashuma** [pkinney/topo#16]
I ran into a need to use `contains?/2` with a `GeometryCollection` as an argument. There is no support for complex geometries, so I implemented a helper to flatten GeometryCollection into non-complex MultiPolygon geometry.

I'm wondering if there is a place in topo for this feature? I'd be happy to contribute.

**Comment by pkinney** [comment]
There's a PR open (#13), but it needs tests and to be extended to the other functions.  If you're up for adding to that, feel free.

Either way, you're not the first person to ask for it, so I will add it to the backlog.

Thanks

**Comment by ilyashuma** [comment]
Thanks for the answer, Powell! I'll spend some time working on this.
