### ISSUE TITLE
It would be useful to have approximate functions

### ISSUE THREAD

**Issue by technomage** [pkinney/topo#3]
It would be useful to have approximate functions such as about_equal?(A,B,Bound) where A and B are geometries, and Bound is the acceptable distance between A and B for equality.  So a square 1mi off from another square would return true for about_equal?(A,B,miles(2)).  Similarly support functions for computing the distance between a point and a line or two points would also allow this type of test, as well as others.

**Comment by pkinney** [comment]
@technomage: There are two ways to do this:

1. Implement a `buffer` function that, given a Geometry and a distance, produces a Polygon or Multipolygon that represents the points within the original Geometry A and all points less than or equal to the given distance from any of those interior points (similar to http://www.postgis.net/docs/ST_Buffer.html).  For your specific use-case (`about_equal?`), you would look for `(A within buffer(B, d)) && (B within buffer(A, d)` which would tell you that A and B are within distance `d` of being equal.  Similar approaches could be used for approximate results for any spatial relationship calculation.
2. Implement a Geometry distance calculation that can calculate the minimum distance between any point within Geometry A and any point within Geometry B. This does not work for your use-case specifically but can be used for `intersects?` or `disjoint?` only.

From a complexity point of view, option 2 is much easier to implement than option 1 and would be much more efficient, but it may not fully satisfy your specific use case.  I'm thinking to create a `geo_distance` module built on-top of the topo and https://github.com/pkinney/distance to calculate minimum distance between two Geometries.
