### ISSUE TITLE
Finding a bounding box

### ISSUE THREAD

**Issue by tiagodavi** [pkinney/topo#9]
Hi. thank you for this amazing library. I would like to know how I can use this library to find a bounding box between 2 pairs of coordinates. Ex I have the input [{lat1, long1}, {lat2,long2}] and would like the bounding box between them as output.

**Comment by pkinney** [comment]
@tiagodavi: you can use https://github.com/pkinney/envelope_ex to find the envelope containing one or more geometries (including two points like you said), but there isn't a clear way to take that envelope and turn it into a geometry.
